### ISSUE TITLE
当座の作業の分担の理解の共有

### ISSUE THREAD

**Issue by hfu** [optgeo/63ants#5]
@hfu が https://github.com/optgeo/a-1 の完成度を高めるのと並行して、@naogify が https://github.com/naogify/atrantic-style を完成させ、FOSS4G ハンズオンの本番では、@hfu が UNVT の概要と a-1 のショートイントロダクションをして、@naogify 中心のハンズオンにつなぐ、という理解で OK ?

**Comment by naogify** [comment]
@hfu はい、その分担で進めれればと思います！
