### ISSUE TITLE
FOSS4G 2021 Japan Online のハンズオンセッション本番での講師の作業分担

### ISSUE THREAD

**Issue by hfu** [optgeo/63ants#9]
1時間を生産に、1時間をスタイルに、1時間を利用に、という大枠は議論できているので、そこを掘り込んでいきます。
コメントを書き換えていく形でも良いと思うので、かためていきましょう。

**Comment by hfu** [comment]
1. 全体説明、UNVTの概要と南極ベクトルタイルの生産・設計（座学、藤村、45分）
2. Charites によるスタイルの変更（ハンズオン、大橋、1時間30分）
3. ハッカソン、というか成果発表（インタラクティブセッション、45分）

こんな感じでどうでしょう＞ @naogify

**Comment by naogify** [comment]
@hfu 
返信遅くなりすみません! ありがとうございます。良いと思います!

> 2. Charites によるスタイルの変更（ハンズオン、大橋、1時間30分）

2の内訳として、
- スタイルについて簡単な説明（20分）
  - fill, line, symbol 等
- [antarctica-style](https://github.com/naogify/antarctica-style)のカスタマイズ手順の説明（20分）
- ハッカソン（参加者の作業時間）（50分）

のような形で考えています。

**Comment by naogify** [comment]
> スタイルについて簡単な説明（20分）

の中身は、この記事のような内容で考えています。

https://gist.github.com/naogify/bb52ac1bf844be6b88fed9fb5b983880

**Comment by hfu** [comment]
@naogify ありがとうございます。イメージがよく分かりました。進めていきましょう❤️‍🔥
